modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="redstone"
version="1.0.0"
displayName="Redstone"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="bart, MCreator"

[[dependencies.redstone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



